[tools]
go = "latest"
lua = "latest"
node = { version = "lts", postinstall = "command -v corepack >/dev/null || npm install -g npm; npm install -g -y corepack && corepack enable pnpm" }
python = "latest"
rust = "latest"
usage = "latest"

[hooks]
enter = "mise install --quiet"

[settings]
experimental = true
jobs = 8

[shell_alias]
p = "pnpm"
pz = "pnpx"
